development:
  adapter: postgresql
  encoding: unicode
  database: bass_app_development
  pool: 5
  username: timcort
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: base_app_test
  pool: 5
  username: timcort
  password: